version: "3.7"
services:
  mongodb:
    image: bp_mongodb
    container_name: bp_mongodb
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    env_file:
      - .env.secrets
      - .env.${ENVIRONMENT}
    volumes:
      - bp-db-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh 127.0.0.1:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s
    restart: unless-stopped

  fastapi:
    image: bp_fastapi
    container_name: bp_fastapi
    depends_on:
      - mongodb
    env_file:
      - .env.secrets
      - .env.${ENVIRONMENT}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "5000:5000"
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 5000


volumes:
  bp-db-data:
    name: bp_db_data
    driver: local
