version: "3.7"
services:
  bp_db:
    image: postgres:15-bookworm
    container_name: bp_db
    volumes:
      - bp-db-data:/var/lib/postgresql/data/pgdata
      - ./secrets:/run/secrets
    env_file:
      - .env
    ports:
      - "5432:5432"

  bp_api:
    container_name: bp_api
    depends_on:
      - bp_db
    volumes:
      - ./secrets:/run/secrets
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "5000:5000"
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 5000


volumes:
  bp-db-data:
    name: bp_db_data
    driver: local
